### ISSUE TITLE
Missing config?

### ISSUE THREAD

**Issue by anderskvist** [jascdk/Nilan_Homeassistant#2]
You seem to have more config for Home Assistant (if looking at the screenshot) that is not in your `config.yaml`?

**Comment by anderskvist** [comment]
The binary sensor for the controller state is missing too

**Comment by jascdk** [comment]
@anderskvist Hi. Thanks for your issue. You are right. The Ping sensor was missing - it is now added to the config. Regarding the UI - you are right. This "code" is not given in the config.yaml. You have to set it up with the Lovelace UI generator which is standard in the newest Hassio version. Thanks for letting me know - i will change the description:)
