### ISSUE TITLE
Bypass doesn't work?

### ISSUE THREAD

**Issue by anderskvist** [jascdk/Nilan_Homeassistant#5]
https://github.com/jascdk/Nilan_Homeassistant/blob/12603cfabc3d05b2b18127a7d1efc0e51d004b7b/config.yaml#L206

Does this work for you? I think this is some kind of relay that opens or closes the bypass valve and you are lucky if you see them set to 1.

```
ventilation/output/BypassOpen 0
ventilation/output/BypassClose 0
```

I tried with the AirBypass.isOpen (address 3000) and it seems to work.

```
ventilation/display/Airbypass.IsOpen 1
```

I have made the changes in my code, so I can quickly make a PR for it :)

By the way, is it possible to communicate with you in an other way, I have some suggestions that might be easier to discuss via IM or mail?

**Comment by jascdk** [comment]
@anderskvist Hi anders:) In my setup it works like it should. I get a 1 or a 0 according the open and close state of the bypass valve. 

![Skærmbillede 2019-05-17 kl  21 18 30](https://user-images.githubusercontent.com/35434108/57951565-afe1c500-78ea-11e9-9579-754ab076bd0a.png)


I cant answer why you are not getting the same values - what system are you running?

Yes sure - you can either contact me on email : jacob.scherrebeck@gmail.com or FB Messenger under Jacob JS :)
